### PR TITLE
Allow Symfony ^4.0

### PR DESCRIPTION
**Pull request by yann-eugone**
Please let me know if there is something else I can do to help.

### CODE REVIEW

**Comment by yann-eugone** [comment]
I do not know your compatibility strategy so I tried to update Travis matrix to test everything, look like it is harder than expected, specialy because phpunit version is not required.

Can someone tell me how I should fix this ?

**Comment by spike31** [comment]
@yann-eugone 
Hi,
Have a look on https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/.travis.yml

The strategy is to test for each php version, each symfony version

Maybe change the phpunit requirements for something like that `"symfony/phpunit-bridge": "^3.4|^4.0",`

**Comment by yann-eugone** [comment]
Maybe it is just me, but do you think that testing something like PHP 7.3 Symfony 2.7 is a good idea ?

**Comment by yann-eugone** [comment]
Tests are green, I had to replace `symfony/phpunit-bridge` with `phpunit/phpunit` to be sure of PHPUnit version

**Comment by spike31** [comment]
@yann-eugone look at this lines 

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/.travis.yml#L5-L13

We don't want to test php 7.3 with sf 2.7

Ah I understand, I said each php version for each sf version. It was a mistake :)

**Comment by gilles-g** [comment]
Nice job!
I will create a release

**Pull request merged**
